version: '3.8'

services:
  user_service:
    build: ./services/user_service
    container_name: user_service
    ports:
      - "8001:8001"
    env_file:
      - ./services/user_service/app/.env
    volumes:
      - .:/app
      - ./.env:/app/.env  # Mount the .env file
    working_dir: /app
    command: bash -c "pip install --no-cache-dir -r services/user_service/requirements.txt && uvicorn services.user_service.app.main:app --host 0.0.0.0 --port 8001 --reload"