"""cart table

Revision ID: 6ffe6aa20220
Revises: 
Create Date: 2024-10-21 15:23:03.715805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ffe6aa20220'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.drop_index('ix_products_stock_quantity', table_name='products')
    # op.drop_table('products')
    # op.drop_table('alembic_version_product_service')
    # op.drop_table('useraddresses')
    # op.drop_table('alembic_version')
    # op.drop_index('ix_product_Images_id', table_name='product_images')
    # op.drop_table('product_images')
    # op.drop_index('ix_product_categories_id', table_name='product_categories')
    # op.drop_table('product_categories')
    # op.drop_table('alembic_version_user_service')
    # op.drop_index('ix_users_phone_number', table_name='users')
    # op.drop_index('ix_users_uuid', table_name='users')
    # op.drop_table('users')
    # ### end Alembic commands ###


# def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=False),
    # sa.Column('otp', mysql.VARCHAR(length=6), nullable=True),
    # sa.Column('is_otp_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    # sa.Column('is_login', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    # sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    # sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    # sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    # sa.Column('profile_image', mysql.VARCHAR(length=512), nullable=True),
    # sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    # sa.Column('dob', sa.DATE(), nullable=True),
    # sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    # sa.Column('refresh_token', mysql.VARCHAR(length=255), nullable=True),
    # sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('uuid', mysql.VARCHAR(length=36), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('ix_users_uuid', 'users', ['uuid'], unique=True)
    # op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=True)
    # op.create_table('alembic_version_user_service',
    # sa.Column('version_num', mysql.VARCHAR(length=32), nullable=False),
    # sa.PrimaryKeyConstraint('version_num'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_table('product_categories',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    # sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    # sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('ix_product_categories_id', 'product_categories', ['id'], unique=False)
    # op.create_table('product_images',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('image_url', mysql.VARCHAR(length=255), nullable=False),
    # sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_images_ibfk_1'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('ix_product_Images_id', 'product_images', ['id'], unique=False)
    # op.create_table('alembic_version',
    # sa.Column('version_num', mysql.VARCHAR(length=32), nullable=False),
    # sa.PrimaryKeyConstraint('version_num'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_table('useraddresses',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('address_type', mysql.VARCHAR(length=50), nullable=False),
    # sa.Column('street_address', mysql.VARCHAR(length=255), nullable=False),
    # sa.Column('city', mysql.VARCHAR(length=50), nullable=False),
    # sa.Column('state', mysql.VARCHAR(length=55), nullable=False),
    # sa.Column('country', mysql.VARCHAR(length=55), nullable=False),
    # sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=False),
    # sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    # sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    # sa.Column('is_default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='useraddresses_ibfk_1'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_table('alembic_version_product_service',
    # sa.Column('version_num', mysql.VARCHAR(length=32), nullable=False),
    # sa.PrimaryKeyConstraint('version_num'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_table('products',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    # sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    # sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('stock_quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    # sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name='products_ibfk_1'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('ix_products_stock_quantity', 'products', ['stock_quantity'], unique=False)
    # op.drop_index(op.f('ix_cart_id'), table_name='cart')
    # op.drop_table('cart')
    # ### end Alembic commands ###
