"""one more column added

Revision ID: 1dbbebdc84fe
Revises: 853e626653ec
Create Date: 2024-10-09 15:22:27.342923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1dbbebdc84fe'
down_revision: Union[str, None] = '853e626653ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=512), nullable=True))
    op.drop_column('users', 'dob')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('users', sa.Column('dob', sa.DATE(), nullable=True))
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
