"""product services table

Revision ID: d1a8cd8b98d1
Revises: c0b2cb3e39b7
Create Date: 2024-10-14 12:17:39.542490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a8cd8b98d1'
down_revision: Union[str, None] = 'c0b2cb3e39b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
