class Message:
    user_greet = "hello welcome to User Services"
    all_well = "All well!!!"
    otp_message = "OTP sent to your phone number"
    logout_message = "User logged out successfully"
    create_message = "Address created successfully"
    update_message = "Address updated successfully"
    delete_message = "Product deleted successfully"
    product_create = "Product created successfully"
    category_delete = "Category deleted successfully "
    product_greet = "hello welcome to Product"
    detail = "Category not found"
    update_detail = "Product not found for the given product ID"
    search_detail = "Product not found"
    id_missing_detail= "Invalid category ID"
    user_detail = "User not found"
    add_missing = "Address not found"
    invalid_otp = "Invalid OTP"
    fail_message = "Failed to create user"

