"""removed one field

Revision ID: 7246530e1803
Revises: 2eb79204a427
Create Date: 2024-10-19 18:07:53.088353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7246530e1803'
down_revision: Union[str, None] = '2eb79204a427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'customizable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('customizable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

